title: Dishwasher simulator
hero_image: images/banner.png
description: Make a dishwashing game in this Code Club Arcade project.
listed: true
pdf: false
steps:
  - title: What you will make
  - title: Start the dishwasher
    completion:
      - engaged
  - title: Add soap and a cloth
  - title: Make one dish appear
  - title: Scrub the dish
  - title: Put it in the rack
  - title: Add the other dishes
  - title: Add music controls
    completion:
      - internal
  - title: Challenge
    challenge: true
    completion:
      - external
